### ISSUE TITLE
Undertow Crash

### ISSUE THREAD

**Issue by DeliciousTea** [ChaosBuffalo/MKUltra#107]
MK Ultra v0.81
Forge v14.23.5.2836
Mods installed: MK Ultra/Targeting API

**Bug**: Casting drown or mass drown while buffed with Undertow crashes the game.
**To reproduce**: Choose Brine Wizard, cast Undertow, cast drown at target.

`java.lang.StackOverflowError: null
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_211]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_211]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_211]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_211]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_211]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:188) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:585) ~[ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:857) ~[vp.class:?]
	at net.minecraft.entity.monster.EntityMob.attackEntityFrom(EntityMob.java:70) ~[ade.class:?]
	at com.chaosbuffalo.mkultra.effects.spells.UndertowPotion.onAttackEntity(UndertowPotion.java:52) ~[UndertowPotion.class:?]
	at com.chaosbuffalo.mkultra.effects.SpellTriggers$ATTACK_ENTITY.lambda$onAttackEntity$0(SpellTriggers.java:250) ~[SpellTriggers$ATTACK_ENTITY.class:?]
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:1.8.0_211]
	at com.chaosbuffalo.mkultra.effects.SpellTriggers$ATTACK_ENTITY.onAttackEntity(SpellTriggers.java:247) ~[SpellTriggers$ATTACK_ENTITY.class:?]
	at com.chaosbuffalo.mkultra.event.CombatEventHandler.onLivingAttackEvent(CombatEventHandler.java:66) ~[CombatEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_424_CombatEventHandler_onLivingAttackEvent_LivingAttackEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:585) ~[ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:857) ~[vp.class:?]
	at net.minecraft.entity.monster.EntityMob.attackEntityFrom(EntityMob.java:70) ~[ade.class:?]
	at com.chaosbuffalo.mkultra.effects.spells.UndertowPotion.onAttackEntity(UndertowPotion.java:52) ~[UndertowPotion.class:?]
	at com.chaosbuffalo.mkultra.effects.SpellTriggers$ATTACK_ENTITY.lambda$onAttackEntity$0(SpellTriggers.java:250) ~[SpellTriggers$ATTACK_ENTITY.class:?]
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:1.8.0_211]
	at com.chaosbuffalo.mkultra.effects.SpellTriggers$ATTACK_ENTITY.onAttackEntity(SpellTriggers.java:247) ~[SpellTriggers$ATTACK_ENTITY.class:?]
	at com.chaosbuffalo.mkultra.event.CombatEventHandler.onLivingAttackEvent(CombatEventHandler.java:66) ~[CombatEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_424_CombatEventHandler_onLivingAttackEvent_LivingAttackEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:585) ~[ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:857) ~[vp.class:?]
	at net.minecraft.entity.monster.EntityMob.attackEntityFrom(EntityMob.java:70) ~[ade.class:?]
	at com.chaosbuffalo.mkultra.effects.spells.UndertowPotion.onAttackEntity(UndertowPotion.java:52) ~[UndertowPotion.class:?]
	at com.chaosbuffalo.mkultra.effects.SpellTriggers$ATTACK_ENTITY.lambda$onAttackEntity$0(SpellTriggers.java:250) ~[SpellTriggers$ATTACK_ENTITY.class:?]
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:1.8.0_211]
	at com.chaosbuffalo.mkultra.effects.SpellTriggers$ATTACK_ENTITY.onAttackEntity(SpellTriggers.java:247) ~[SpellTriggers$ATTACK_ENTITY.class:?]
	at com.chaosbuffalo.mkultra.event.CombatEventHandler.onLivingAttackEvent(CombatEventHandler.java:66) ~[CombatEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_424_CombatEventHandler_onLivingAttackEvent_LivingAttackEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:585) ~[ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:857) ~[vp.class:?]
	at net.minecraft.entity.monster.EntityMob.attackEntityFrom(EntityMob.java:70) ~[ade.class:?]
	at com.chaosbuffalo.mkultra.effects.spells.UndertowPotion.onAttackEntity(UndertowPotion.java:52) ~[UndertowPotion.class:?]
	at com.chaosbuffalo.mkultra.effects.SpellTriggers$ATTACK_ENTITY.lambda$onAttackEntity$0(SpellTriggers.java:250) ~[SpellTriggers$ATTACK_ENTITY.class:?]
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:1.8.0_211]`

This sort of error goes on repeatedly until the game completely locks up. Seems related to the other bug I posted with Flame Blade, but not 100% sure.

**Comment by Kovak** [comment]
This is fixed in the 0.82 release on curseforge.
